### ISSUE TITLE
Issue: Apache Validation Error

### ISSUE THREAD

**Issue by DerSchwarzeJugo** [custom-dev-tools/wampserver-ssl-auto-config#11]
**Issue**

Running into an apache Validation Error when trying to run script (in windows 10, tried with both: powershell and cmd).

Configuration File has been Setup as following:

```ini
;--------------------------;
; WampServer Configuration ;
;--------------------------;

; Your WampServer installation path.
wampServerInstallPath=C:\wamp64

; Your custom path to store your SSL certificates, keys, logs and vhost files.
; Ensure this path is NOT within your WampServer installation path.
wampServerExtensionsPath=C:\wamp64 - ssl auto config

;-------------------------;
; SSL Certificate Details ;
;-------------------------;

; These (common) ssl certificate details are used to build each developments domain name certificate.
;
; sslCity:             The full name of a city.
; sslState:            The full name of a state.
; sslCountry:          The two letter ISO code of a country.
; sslOrganisation:     The organisation name.
; sslOrganisationUnit: The unit name of a organisation.
; sslEmail:            Use the 'local' part of an email address followed by the @ (at) symbol only.
;                      IMPORTANT: Do not include the 'domain' part of the email address as the hostname will be auto-appended.
; sslDays:             The number of days you would like the certificates to remain valid for.

sslCity=City
sslState=State
sslCountry=US
sslOrganization=Some
sslOrganizationUnit=Development
sslEmail=mail@mail.com
sslDays=3650

;---------------------;
; Development Domains ;
;---------------------;

[Localhost]
hostname=localhost
documentRoot=c:/wamp64/www
http2=true
```

**To Reproduce**

1. Run Script'
2. See error

**Expected behavior**

Script should run through correctly

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Windows 10
 - apache2.4.54.2

**Additional context**

***Console Ouput:***

```
  WampServer SSL Auto Config (v1.2.3)
  -----------------------------------

  15:48:36.94 : Parsed configuration file.
  15:48:36.95 : Common 'logs' directory already exists.
  15:48:36.97 : Script initialised.
  15:48:36.99 : ---------------------------------------------
  15:48:37.02 : Found WampServer installation path.
  15:48:37.04 : Found WampServer Apache path.
  15:48:37.05 : Found WampServer Apache installation(s):
  15:48:37.09 :   'apache2.4.54.2'
  15:48:37.11 : Found OS 'hosts' file.
  15:48:37.16 : Found OS Apache service name.
  15:48:37.17 : Validating Apache config file(s):
  15:48:37.77 :   'apache2.4.54.2'
  15:48:37.80 : Using 'openssl.exe' from 'apache2.4.54.2'
  15:48:37.85 : Apache service already started.
  15:48:37.88 : OS 'hosts' file backed up.
  15:48:37.90 : Backing up Apache 'httpd.conf' file(s):
  15:48:37.93 :   'apache2.4.54.2'
  15:48:37.95 : Common 'certs' directory already exists.
  15:48:37.96 : Common 'vhosts\http' directory already exists.
  15:48:37.97 : Common 'vhosts\https' directory already exists.
  15:48:38.00 : Re-created common 'httpd-ssl.conf' file.
  15:48:38.02 : ---------------------------------------------
  15:48:38.04 : Localhost (localhost)
  15:48:38.06 :   'certs' directory already exists.
  15:48:38.08 :   'logs' directory already exists.
  15:48:38.12 :   Re-created 'openssl.cnf' file.
  15:48:38.16 :   Re-created Virtual Host http file.
  15:48:38.20 :   Re-created Virtual Host https file.
  15:48:38.26 :   Deleted old certificate from store.
  15:48:38.37 :     Generated certificate keys.
  15:48:38.41 :     Removed certificate passphrase.
  15:48:38.47 :     Generated Certificate.
  15:48:38.49 :     Deleted 'private.pem' file.
  15:48:38.55 :   Added new certificate to store.
  15:48:38.60 :   Attempting to add hostname to OS 'hosts' file.
  15:48:38.67 :   Hostname added to OS 'hosts' file.
  15:48:38.69 : ---------------------------------------------
  15:48:38.71 : Updating Apache primary config file(s):
  15:48:38.73 :   'apache2.4.54.2\conf\httpd.conf'
  15:48:38.83 :     'socache_shmcb_module' already uncommented.
  15:48:38.91 :     'ssl_module' already uncommented.
  15:48:42.52 :     'http2_module' uncommented.
  15:48:42.61 :     Added SSL Config link.
  15:48:42.69 :     Added HTTP vhosts link.
  15:48:42.77 :     Added HTTPS vhosts link.

  -----------------------------------------------------------

                            FAILURE

  -----------------------------------------------------------

  WampServer Apache Validation Error

  File:  See below
  Error: AH00526: Syntax error on line 4 of C:/wamp64 - ssl auto config/vhosts/https/conf/httpd-ssl.conf:

  Please correct the error in the stated configuration file and restart WampServer.

  -----------------------------------------------------------

  Press any key to exit.
```
  
***C:/wamp64 - ssl auto config/vhosts/https/conf/httpd-ssl.conf***

```
Listen 443

#   SSL Cipher Suite:
SSLCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
SSLProxyCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES

#  Enforce the server's cipher order.
SSLHonorCipherOrder on

#   SSL Protocol support:
SSLProtocol all -SSLv3
SSLProxyProtocol all -SSLv3

#   Pass Phrase Dialog:
SSLPassPhraseDialog  builtin

#   Inter-Process Session Cache:
SSLSessionCache        "shmcb:c:/Apache24/logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300
```

**Comment by custom-dev-tools** [comment]
Hi @DerSchwarzeJugo

It looks like this is the not the first time you have run the `ssl_config.bat` script.

Did you have any problems with the script / output when you ran it for the very first time?

Your output indicates there was no backup of `apache2.4.54.2`. If there was a backup present it would have displayed `'apache2.4.54.2' already backed up.`

The very first time you run `ssl_config.bat` (or after installing a new Apache version) the script should generate a backup of the WampServer Apache `httpd.conf` file(s), named `httpd-backup.conf`. Yours appears not to be there. Did you happen to manually delete it at any time?

Having this backup file allows us to quickly restore the Apache `httpd.conf` when things go wrong.

Can you please add to this thread the last dozen or so lines of your `C:\wamp64\bin\apache\apache2.4.54.2\conf\httpd.conf` file. They should look like something below.

```conf
# SSL Config - Additional
Include "C:\wamp64 - ssl auto configs/vhosts/https/conf/httpd-ssl.conf"

# HTTP Vhost(s) - Additional
Include "C:\wamp64 - ssl auto config/vhosts/http/*.conf"

# HTTPS Vhost(s) - Additional
Include "C:\Wwamp64 - ssl auto config/vhosts/https/*.conf"
```

---

As a side note, within your `config.ini` file please update the `sslEmail` line from `sslEmail=mail@mail.com` to `sslEmail=mail@`. IE: Remove `mail.com`

---

In the meantime, I will test WampServer Apache version 2.4.54.2 and see if it plays nicely with the stated SSL Cipher Suits on line 4. IE: `SSLCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES`

**Comment by custom-dev-tools** [comment]
Hi @DerSchwarzeJugo

I just updated my WampServer to the latest version (being v3.3.1), installed the Microsoft Visual C++ Redistributable Package 2022 (VS17, both 32-bit and 64-bit) and installed Apache version 2.4.54.2

The `ssl_config.bat` script worked as expected. No issues or errors.

My Apache 2.4.54.2 `httpd.conf` file was backed up without issue, then the (original) `httpd.conf` file was updated with the correct lines of code at EOF (end of file), ensuring all other custom `.conf` files are loaded and read / processed. All `.conf` files passed validation. Therefore, there must be no issue with the stated SSL Cipher Suits on line 4 of `C:/wamp64 - ssl auto config/vhosts/https/conf/httpd-ssl.conf`.

If need be, may I suggest you update your WampServer to the latest version and install Redistributable Package 2022 (if not already installed) as Apache 2.4.54.2 will need it to function correctly.

Additionally, as you don’t have the initial backup of the Apache 2.4.54.2 `httpd.conf` file, I recommend you delete the `C:\wamp64\bin\apache\apache2.4.54.2\conf\httpd.conf` file (plus the `httpd-backup.conf` file if it exists) and then reinstall the Apache 2.4.54.2 addon.

Let me know how you go and what results you get.

**Comment by DerSchwarzeJugo** [comment]
It seem like these two lines were not uncommented in httpd.conf

```
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so
```

uncommenting these manually after running the script, did resolve the issue with the syntax error.

weirdly in the script output it says, that these two lines are already uncommented, but they are not

**Comment by custom-dev-tools** [comment]
Hi @DerSchwarzeJugo

Thanks for the feedback.

On `restore`, automatic deletion of the backup file(s) occurs so that it working. :heavy_check_mark:

The Output of the last few lines of `httpd.conf` is correct. :heavy_check_mark:

I will check the "uncomment" logic at [line 752](https://github.com/custom-dev-tools/wampserver-ssl-auto-config/blob/53f51e3711ac92cf40b5709cf9e854a22127fd74/ssl_config.bat#L752) and [line 772](https://github.com/custom-dev-tools/wampserver-ssl-auto-config/blob/53f51e3711ac92cf40b5709cf9e854a22127fd74/ssl_config.bat#L772C14-L772C14) to confirm correct operation.

That said, interesting that [line 793](https://github.com/custom-dev-tools/wampserver-ssl-auto-config/blob/53f51e3711ac92cf40b5709cf9e854a22127fd74/ssl_config.bat#L793C8-L793C8) seemed to work for you without issue.

Thanks @DerSchwarzeJugo for your debugging and use of this script. :smiley:

**Comment by custom-dev-tools** [comment]
Hi @DerSchwarzeJugo

I commented out in my `httpd.conf` file both lines you mentioned that you found commented out in your `httpd.conf` file.

`C:\Wamp64\bin\apache\apache2.4.54.2\conf\httpd.conf`

```
077  |  #
078  |  # Dynamic Shared Object (DSO) Support
079  |  #
...
185  |  #LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
...
187  |  #LoadModule ssl_module modules/mod_ssl.so
```
---

Running the `ssl_config.bat` script resulted in the same failure as you received, though my script failed during the very first Apache config validation step. Uncommenting these lines again results in a functioning script.

This is an interesting failure to note, being:

- Commenting out the `mod_socache_shmcb.so` (Session) module whilst still having reference to the `httpd-ssl.conf` file in `httpd.conf` results in the below error:

  `Error: AH00526: Syntax error on line 18 of C:/wamp64 - ssl auto config/vhosts/https/conf/httpd-ssl.conf`

- Commenting out the `mod_ssl.so` (SSL) module whilst still having reference to the `httpd-ssl.conf` file in `httpd.conf` results in the below error:

  `Error: AH00526: Syntax error on line 4 of C:/wamp64 - ssl auto config/vhosts/https/conf/httpd-ssl.conf`

---

`C:/wamp64 - ssl auto config/vhosts/https/conf/httpd-ssl.conf`

```
01  |  Listen 443
02  |
03  |  #   SSL Cipher Suite:
04  |  SSLCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
05  |  SSLProxyCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
06  |
07  |  #   Enforce the server's cipher order.
08  |  SSLHonorCipherOrder on
09  |
10  |  #   SSL Protocol support:
11  |  SSLProtocol all -SSLv3
12  |  SSLProxyProtocol all -SSLv3
13  |
14  |  #   Pass Phrase Dialog:
15  |  SSLPassPhraseDialog  builtin
16  |
17  |  #   Inter-Process Session Cache:
18  |  SSLSessionCache        "shmcb:c:/Apache24/logs/ssl_scache(512000)"
19  |  SSLSessionCacheTimeout  300
```

---

Whilst I am unsure how this misconfiguration (IE: Commenting out) of your `httpd.conf` file came to be, future debugging will be assisted by this issue.

**Comment by DerSchwarzeJugo** [comment]
hi @custom-dev-tools i am happy that i could provide some help :)
Many thanks to you, since this is a very useful and handy tool and I will gladly recommend it to all wamp users that need https access.
