### ISSUE TITLE
 WampServer Apache Service Startup Error

### ISSUE THREAD

**Issue by kaurotuan** [custom-dev-tools/WampServer-SSL-Auto-Config#2]
WampServer SSL Auto Config (v1.1.1)
  -----------------------------------

  11:51:02,41 : Parsed configuration file.
  11:51:02,43 : Common 'logs' directory already exists.
  11:51:02,44 : Script initialised.
  11:51:02,46 : ---------------------------------------------
  11:51:02,48 : Found WampServer installation path.
  11:51:02,49 : Found WampServer Apache path.
  11:51:02,51 : Found WampServer Apache installation(s):
  11:51:02,54 :   'apache2.4.46'
  11:51:02,55 : Found OS 'hosts' file.
  11:51:02,59 : Found OS Apache service name.
  11:51:02,60 : Validating Apache config file(s):
  11:51:02,94 :   'apache2.4.46'
  11:51:02,96 : Using 'openssl.exe' from 'apache2.4.46'
  11:51:03,01 : Starting Apache service.

  -----------------------------------------------------------

                            FAILURE

  -----------------------------------------------------------

  WampServer Apache Service Startup Error

  File:  See below
  Error: Unknown

  Please correct the error and restart WampServer.

  -----------------------------------------------------------

  Press any key to exit.

**Comment by custom-dev-tools** [comment]
Hi Kaurotuan

Could you please attach the "ssl_config.log" file found in the "logs" path?

This will give me a little bit more information to help us debug the issue.

Additionally, do you know if the Apache service is running or previously stopped when you get this error?

Thanks Kaurotuan

**Comment by kaurotuan** [comment]
![image](https://user-images.githubusercontent.com/48125661/100384089-11194700-2ffe-11eb-8e95-50dd6bb3ef99.png)

Não cria arquivo de LOG, mas segue abaixo o arquivo do config que estou usando:

;--------------------------;
; WampServer Configuration ;
;--------------------------;

; Your WampServer installation path.
wampServerInstallPath=C:\wamp64

; The parent path where your SSL certificates, keys, vhost and log files will be stored.
wampServerExtensionsPath=C:\wamp64\bin\apache\apache2.4.46\conf\key

;-------------------------;
; SSL Certificate Details ;
;-------------------------;

; These (common) ssl certificate details are used to build each developments domain name certificate.
;
; sslCity:             The full name of a city.
; sslState:            The full name of a state.
; sslCountry:          The two letter ISO code of a country.
; sslOrganisation:     The organisation name.
; sslOrganisationUnit: The unit name of a organisation.
; sslEmail:            Use the 'local' part of an email address followed by the @ (at) symbol only.
;                      IMPORTANT: Do not include the 'domain' part of the email address as the hostname will be auto-appended.
; sslDays:             The number of days you would like the certificates to remain valid for.

sslCity=Brasília
sslState=Distrito Federal
sslCountry=BR
sslOrganization=i2br informática
sslOrganizationUnit=Departamento de TI
sslEmail=junior@i2br.com.br
sslDays=3650

;---------------------;
; Development Domains ;
;---------------------;

[Website 1]
hostname=localhost
documentRoot=C:/wamp64/www/

[Website 2]
hostname=i2br.com.br
documentRoot=C:/wamp64/www/

**Comment by custom-dev-tools** [comment]
Hi Kaurotuan

By the looks of your "config.ini" file, the log file ("ssl_config.log") should be located in your "C:\wamp64\bin\apache\apache2.4.46\conf\key\logs" directory.

Initial thoughts indicate a problem with the "net start" command trying to start your WampServer service. Are you sure you are running Apache as a service? To test this right-click the WampServer Tray icon -> Tools -> Check state of services

Press "Y" and then press "Enter" to copy the output to the clipboard, then paste the results here in the comments.

---

Some pointers for your "config.ini" file:

1. Best to point the "wampServerExtensionsPath" directory to a path outside of the WampServer directory, just in case you remove "apache2.4.4" at some point in the future.

2. The value of "sslEmail" should be truncated after the "@" symbol: EG: sslEmail=junior@

3. No need to include the [Website 1] section in your config file as "localhost" is already configured in another WampServer .conf file. FYI - .conf files cascade, just like CSS.

**Comment by custom-dev-tools** [comment]
Hi Kaurotuan

As I haven't received a response regarding the above issue for over 30 days now I'm going to assume that your issue has been resolved.

If not, just open a new issue so we may continue to investigate the problem.

Thank you.
