### ISSUE TITLE
folder was unexpected at this time.

### ISSUE THREAD

**Issue by marksamfd** [custom-dev-tools/WampServer-SSL-Auto-Config#3]
cant pass this any ideas

**Comment by custom-dev-tools** [comment]
Hi Mark

Thanks for reporting this issue.

I am unsure where this error message may have originated from.

Can you please reply with the latest output from your "ssl_config.log".

This log file should be found in the below directory if you used the default "wampServerExtensionPath" setting found under the "WampServer Configuration" section in the "sample-config.ini" file. (PS: Line 9 of the "sample-config.ini" file is where this setting can be found).

`
C:\wamp64 - ssl auto config\logs\ssl_config.log
`

**NOTE:** If your "ssl_config.log" log file is huge, delete it and then run the script again prior to posting.

Thank you.

**Comment by custom-dev-tools** [comment]
Hi Mark

As I haven't received a response regarding the above issue for over 30 days now I'm going to assume that your issue has been resolved.

If not, just open a new issue so we may continue to investigate the problem.

Thank you.
