### ISSUE TITLE
WampServer Apache Validation Error

### ISSUE THREAD

**Issue by RacerXx** [custom-dev-tools/wampserver-ssl-auto-config#6]
## Issue

Please describe the issue you are having.
dont work
## Log File Output
 WampServer SSL Auto Config (v1.2.2)
  -----------------------------------

  22:31:16.43 : Parsed configuration file.
  22:31:16.44 : Created common 'logs' directory.
  22:31:16.45 : Script initialised.
  22:31:16.47 : ---------------------------------------------
  22:31:16.48 : Found WampServer installation path.
  22:31:16.50 : Found WampServer Apache path.
  22:31:16.51 : Found WampServer Apache installation(s):
  22:31:16.53 :   'apache2.4.33'
  22:31:16.54 : Found OS 'hosts' file.
  22:31:16.57 : Found OS Apache service name.
  22:31:16.58 : Validating Apache config file(s):
  22:31:16.93 :   'apache2.4.33'
  22:31:16.95 : Using 'openssl.exe' from 'apache2.4.33'
  22:31:16.98 : Apache service already started.
  22:31:17.00 : OS 'hosts' file already backed up.
  22:31:17.01 : Backing up Apache 'httpd.conf' file(s):
  22:31:17.03 :   'apache2.4.33' already backed up.
  22:31:17.04 : Created common 'certs' directory.
  22:31:17.05 : Created common 'vhosts\http' directory.
  22:31:17.06 : Created common 'vhosts\https' directory.
  22:31:17.07 : Created common 'httpd-ssl.conf' file.
  22:31:17.09 : ---------------------------------------------
  22:31:17.10 : Website 1 (;--------------------------;)
  22:31:17.11 :   'certs' directory created.
  22:31:17.13 :   'logs' directory created.
  22:31:17.15 :   Created 'openssl.conf' file.
  22:31:17.17 :   Created Virtual Host http file.
  22:31:17.20 :   Created Virtual Host https file.
  22:31:17.25 :   Deleted old certificate from store.
  22:31:17.29 :     Generated certificate keys.
  22:31:17.32 :     Removed certificate passphrase.
  22:31:17.36 :     Generated Certificate.
  22:31:17.38 :     Deleted 'private.pem' file.
  22:31:17.41 :   Added new certificate to store.
  22:31:17.45 :   Attempting to add hostname to OS 'hosts' file.
  22:31:17.49 :   Hostname added to OS 'hosts' file.
  22:31:17.50 : ---------------------------------------------
  22:31:17.52 : Website 1 (wowbladez.ddns.net)
  22:31:17.53 :   'certs' directory created.
  22:31:17.55 :   'logs' directory created.
  22:31:17.57 :   Created 'openssl.conf' file.
  22:31:17.59 :   Created Virtual Host http file.
  22:31:17.62 :   Created Virtual Host https file.
  22:31:17.66 :   Deleted old certificate from store.
  22:31:17.75 :     Generated certificate keys.
  22:31:17.79 :     Removed certificate passphrase.
  22:31:17.82 :     Generated Certificate.
  22:31:17.84 :     Deleted 'private.pem' file.
  22:31:17.88 :   Added new certificate to store.
  22:31:17.92 :   Attempting to add hostname to OS 'hosts' file.
  22:31:17.96 :   Hostname added to OS 'hosts' file.
  22:31:17.97 : ---------------------------------------------
  22:31:17.99 : Website 2 (wowbladez.ddns.net)
  22:31:18.00 :   'certs' directory already exists.
  22:31:18.01 :   'logs' directory already exists.
  22:31:18.04 :   Re-created 'openssl.cnf' file.
  22:31:18.06 :   Re-created Virtual Host http file.
  22:31:18.09 :   Re-created Virtual Host https file.
  22:31:18.13 :   Deleted old certificate from store.
  22:31:18.36 :     Generated certificate keys.
  22:31:18.40 :     Removed certificate passphrase.
  22:31:18.43 :     Generated Certificate.
  22:31:18.45 :     Deleted 'private.pem' file.
  22:31:18.49 :   Added new certificate to store.
  22:31:18.52 :   Hostname already added to OS 'hosts' file.
  22:31:18.54 : ---------------------------------------------
  22:31:18.55 : Updating Apache primary config file(s):
  22:31:18.57 :   'apache2.4.33\conf\httpd.conf'
  22:31:18.63 :     'socache_shmcb_module' already uncommented.
  22:31:18.69 :     'ssl_module' already uncommented.
  22:31:18.74 :     'http2_module' already uncommented.
  22:31:18.80 :     Added SSL Config link.
  22:31:18.86 :     Added HTTP vhosts link.
  22:31:18.92 :     Added HTTPS vhosts link.

  -----------------------------------------------------------

                            FAILURE

  -----------------------------------------------------------

  WampServer Apache Validation Error

  File:  See below
  Error: AH00526: Syntax error on line 8 of C:/wamp6431/bin/apache/apache2.4.33/conf/original/extra - ssl auto config/vhosts/http/;--------------------------;.conf:

  Please correct the error in the stated configuration file and restart WampServer.

  -----------------------------------------------------------

  Press any key to exit.
1. Locate the `ssl_config.log` log file.

   > Default location is: `C:\wamp64 - ssl auto config\logs\ssl_config.log`
   > 
   > Custom base directory location is set on line 9 of your config.ini file. 

2. Attach the `ssl_config.log` file to this issue.
[https://pastebin.com/znidL4nM](url)
## Environment

Please provide the following version numbers.
- Microsoft Windows Version:win 10
- WampServer Version: 3.1.3
- WampServer SSL Auto Config Script Version: v1.2.2
  
## Additional Information

Please add any additional information that may help resolve this issue.
no matter what i set config file wampServerExtensionsPath=C:\wamp6431\bin\apache\apache2.4.33\conf\original\extra - ssl auto config it fails. running with admin perms and fresh wamp server

**Comment by RacerXx** [comment]
nvm i found the problem but im leaving the issue open. I would like you to reword or clarify the comment on line 8 of the *ini file. in my case line 9 is wampServerExtensionsPath=C:\wamp6431\bin\apache\apache2.4.51\modules. Line 8 should simply say "path to apache modules"

**Comment by custom-dev-tools** [comment]
Hi @RacerXx

The path defined in line 9 of the config file (`wampServerExtensionsPath=`) should not point to any folder in the WampServer installation directory.

This path is for you to define a custom location (outside of the WampServer installation directory) which Apache will use to reference the newly created SSL certificates, logs and vhost files.

That said, I will clarify line 8 in the config file to try and remove any ambiguity.

Thanks for raising the issue.

**Comment by custom-dev-tools** [comment]
Updated explanation of wampServerExtensionsPath in configuration file and README.md
