### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by GerryGit** [custom-dev-tools/wampserver-ssl-auto-config#9]
Experiencing the error message below after successful validation.
I find in C:\wamp64 - ssl auto config\vhosts\http\ an empty folder
and in C:\wamp64 - ssl auto config\vhosts\https\conf an httpd-ssl.conf

 WampServer SSL Auto Config (v1.2.3)
  -----------------------------------

  22:50:50.62 : Parsed configuration file.
  22:50:50.63 : Common 'logs' directory already exists.
  22:50:50.64 : Script initialised.
  22:50:50.66 : ---------------------------------------------
  22:50:50.68 : Found WampServer installation path.
  22:50:50.70 : Found WampServer Apache path.
  22:50:50.71 : Found WampServer Apache installation(s):
  22:50:50.74 :   'apache2.4.54.2'
  22:50:50.77 : Found OS 'hosts' file.
  22:50:50.80 : Found OS Apache service name.
  22:50:50.81 : Validating Apache config file(s):

  -----------------------------------------------------------

                            FAILURE

  -----------------------------------------------------------

  WampServer Apache Validation Error

  File:  See below
  Error: httpd.exe: Syntax error on line 597 of C:/wamp64/bin/apache/apache2.4.54.2/conf/httpd.conf: Include/IncludeOptional: No matches for the wildcard '*.conf' in 'C:/wamp64 - ssl auto config/vhosts/http', failing

  Please correct the error in the stated configuration file and restart WampServer.

  -----------------------------------------------------------

  Press any key to exit.

Appreciate some guidance on this issue.

**Comment by custom-dev-tools** [comment]
Hi @GerryGit 

Could you please add your config file to this thread.

As this is not the first time you have run `ssl_config.bat`, did it work the very first time you ran it?

It looks like your `[host-name].conf` file is missing from the designated directory (being `C:/wamp64 - ssl auto config/vhosts/http`).

May you have accidently deleted `C:/wamp64 - ssl auto config/vhosts/http/[host-name].conf` ?

You should have a minimum of one `[host-name].conf` file in both the `http` and `https` directories, as shown below:

- `C:/wamp64 - ssl auto config/vhosts/http/[host-name].conf`
- `C:/wamp64 - ssl auto config/vhosts/https/[host-name].conf`

Let me know if they exist.

**Comment by GerryGit** [comment]
The folders do exist as follows:
C:\wamp64 - ssl auto config\vhosts\https\conf
httpd-ssl.conf contents:

Listen 443

#   SSL Cipher Suite:
SSLCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
SSLProxyCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES

#  Enforce the server's cipher order.
SSLHonorCipherOrder on

#   SSL Protocol support:
SSLProtocol all -SSLv3
SSLProxyProtocol all -SSLv3

#   Pass Phrase Dialog:
SSLPassPhraseDialog  builtin

#   Inter-Process Session Cache:
SSLSessionCache        "shmcb:c:/Apache24/logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300

and 
C:\wamp64 - ssl auto config\vhosts\http
which is empty


Neither of them contain [host-name].conf files

I did not delete them. Is it possible to add them manually?

**Comment by custom-dev-tools** [comment]
Hi @GerryGit

Could you please add the below listed files to this thread to assist in debugging.

- `config.ini` (See "readme.md" [here](https://github.com/custom-dev-tools/wampserver-ssl-auto-config?tab=readme-ov-file#configuration) for more information)
- `ssl_config.log`

Thank you.

**Comment by custom-dev-tools** [comment]
Hi @GerryGit 

As I haven't received a response regarding the above issue for over 30 days now I'm going to assume that your issue has been resolved.

If not, just open a new issue so we may continue to investigate the problem.

Thank you.
